#!bin/sh

# Update mirror list
sudo pacman-mirrors --country Sweden,Norway,Germany,Finland && sudo pacman Syyu

# Installs
sudo pacman -S i3-gaps i3status dmenu zsh fzf autotiling arandr zsh-syntax-highlighting nodejs npm feh compton neovim github-cli tk
sudo pacman -Fy gitk
# Misc
# Setup github cli auth
gh auth login

# Git clones
# TODO
